using System;

using Rust;

namespace Oxide.Plugins
{
    [Info("NoSleepers", "Wulf/lukespragg", "0.4.1", ResourceId = 1452)]
    [Description("Disables sleepers by killing players on quit")]

    class NoSleepers : RustPlugin
    {
        // Do NOT edit this file, instead edit NoSleepers.json in oxide/config

        #region Initialization

        void OnServerInitialized()
        {
            LoadDefaultConfig();
            if (!killExisting) return;

            var killCount = 0;
            var sleepers = BasePlayer.sleepingPlayerList;
            foreach (var sleeper in sleepers.ToArray())
            {
                if (sleeper.IsDead()) sleepers.Remove(sleeper);
                sleeper.KillMessage();
                killCount++;
            }
            if (killCount > 0) Puts($"Killed {killCount} {(killCount == 1 ? "sleeper" : "sleepers")}");
        }

        #endregion

        #region Configuration

        bool killExisting;
        bool removeCorpses;

        protected override void LoadDefaultConfig()
        {
            Config["KillExisting"] = killExisting = GetConfig("KillExisting", true);
            Config["RemoveCorpses"] = removeCorpses = GetConfig("RemoveCorpses", true);
            SaveConfig();
        }

        #endregion

        #region Sleeper/Corpse Removal

        void OnPlayerInit(BasePlayer player)
        {
            if (player.IsDead()) player.Respawn();
        }

        void OnPlayerRespawned(BasePlayer player)
        {
            if (player.IsSleeping()) player.EndSleeping();
        }

        void OnPlayerDisconnected(BasePlayer player)
        {
            if (player.IsDead()) player.Hurt(1000f, DamageType.Suicide, player, false);
        }

        //object OnPlayerSleep(BasePlayer player) => true;

        void OnEntitySpawned(BaseNetworkable entity)
        {
            if (removeCorpses && entity.ShortPrefabName.Equals("player_corpse")) entity.KillMessage();
        }

        #endregion

        #region Helpers

        T GetConfig<T>(string name, T value) => Config[name] == null ? value : (T)Convert.ChangeType(Config[name], typeof(T));

        #endregion
    }
}
